name: Generate project JSDoc documentation

on:
  push:
    if: github.event.pull_request.merged == true

jobs:
  build_jsdoc:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      - name: Download Maindoc project
        uses: actions/checkout@v2
        with:
          repository: sebastian-palma/maindoc
          path: maindoc
          token: ${{ secrets.PAT }}

      - name: Download Jsdoc template
        uses: actions/checkout@v2
        with:
          repository: sebastian-palma/docdash
          path: docdash
          token: ${{ secrets.PAT }}
          ref: ft/maindoc/init

      - name: Generate Jsdoc documentation
        run: |
          npm install -g jsdoc
          jsdoc -r . -c ./.jsdoc.conf.json -t docdash
          mkdir -p app/views/docs/jsdoc/doctest/
          mv out/ app/views/docs/jsdoc/doctest/
        env:
          USERNAME: github-actions
          REPO_KEY: ${{ secrets.PAT }}

      - name: Pushes to another repository
        uses: sebastian-palma/github-action-push-to-another-repository@allow-creating-destination-directory
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          destination-repository-directory: 'app/views/docs/jsdoc/doctest/'
          source-directory: 'out'
          create-destination-directory: true
          destination-github-username: 'sebastian-palma'
          destination-repository-name: 'maindoc'
          target-branch: main
          user-email: github-actions
