name: Generate and push project documentation

env:
  CURRENT_BRANCH: ${{ github.event.client_payload.pull_request.head.ref }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}

on:
  repository_dispatch:
    types: [update_docs-command]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.52.0
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      # `with` options must be set after Ruby (at least)
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Change dir to current branch
        run: git checkout $CURRENT_BRANCH

      - name: Download Maindoc project
        uses: actions/checkout@v2
        with:
          repository: sebastian-palma/maindoc
          path: maindoc
          token: ${{ secrets.PAT }}

      - name: Download JSDoc template
        uses: actions/checkout@v2
        with:
          repository: sebastian-palma/docdash
          path: docdash
          token: ${{ secrets.PAT }}
          ref: ft/maindoc/init

      - name: Download YARD template
        uses: actions/checkout@v2
        with:
          repository: sebastian-palma/yard-template
          path: yard-template
          token: ${{ secrets.PAT }}

      - name: Clean destination directories
        run: |
          rm -rf maindoc/app/views/docs/jsdoc/${REPOSITORY_NAME}/
          rm -rf maindoc/app/views/docs/yard/${REPOSITORY_NAME}/

      - name: Install documentation libraries
        run: |
          npm install -g jsdoc
          gem install yard

      - name: Generate JSDoc documentation
        run: jsdoc -r . -c .jsdoc.conf.json -t docdash

      - name: Generate YARD documentation
        run: yardoc --no-cache --no-save --protected --private -p yard-template app/controllers/**/*.rb \
                                                                                app/helpers/**/*.rb     \
                                                                                app/jobs/**/*.rb        \
                                                                                app/mailers/**/*.rb     \
                                                                                app/models/**/*.rb      \
                                                                                app/services/**/*.rb

      - name: Move documentation files to wrapper application
        run: |
          cp -r out/ maindoc/app/views/docs/jsdoc/${REPOSITORY_NAME}/
          cp -r doc/ maindoc/app/views/docs/yard/${REPOSITORY_NAME}/
          cp rspec_api_documentation/open_api.json maindoc/app/javascript/packs/swagger/ui/specs/${REPOSITORY_NAME}.json
          cp rspec_api_documentation/open_api.json maindoc/app/javascript/packs/swagger/editor/specs/${REPOSITORY_NAME}.json

      - name: Push documentation changes
        run: |
          cd maindoc
          git config user.name github-actions
          git config user.email actions@github.com
          git add --all
          git commit -m "Update ${REPOSITORY_NAME} documentation."
          git push https://github-actions:$REPO_KEY@github.com/sebastian-palma/maindoc.git
        env:
          REPO_KEY: ${{ secrets.PAT }}
